"""
title: Hermes Trace Pipe
author: Nicolás Ramos
version: 2.3
license: MIT
description: Connect Open WebUI to the Hermes Agent API server and translate the agent's reasoning/execution trace (tool calls and results) into standard OpenAI chunks — reasoning_content for the Thinking block and markdown URLs (with direct download links) for generated images.
requirements: requests
"""

import json
import re

import requests
from pydantic import BaseModel, Field


class Pipeline:
    class Valves(BaseModel):
        HERMES_BASE_URL: str = Field(
            default="http://192.168.1.18:8642/v1",
            description="Base URL of the Hermes API server (OpenAI-compatible)",
        )
        HERMES_API_KEY: str = Field(
            default="266e5532bc2343a1a3715ebacde65b4aa6be9601e512f237af07e269b2539539",
            description="API_SERVER_KEY of the Hermes gateway",
        )
        IMAGES_BASE_URL: str = Field(
            default="http://192.168.1.18:8787",
            description="Public URL of the static server serving images generated by Hermes (~/.hermes/cache/images)",
        )
        MAX_RESULT_CHARS: int = Field(
            default=1500,
            description="Max characters of each tool result shown in the reasoning block",
        )

    def __init__(self):
        self.id = "hermes_trace"
        self.name = "Hermes (with trace)"
        self.valves = self.Valves()

    def _chunk(self, delta: dict):
        return {
            "choices": [{"index": 0, "delta": delta, "finish_reason": None}]
        }

    def _image_md(self, name: str) -> str:
        """Markdown para una imagen: vista inline + enlace de descarga directa."""
        base = self.valves.IMAGES_BASE_URL.rstrip("/")
        return f"![{name}]({base}/{name})\n\n[⬇️ Descargar imagen]({base}/download/{name})"

    def _fix_image_paths(self, text: str) -> str:
        """Convert local image paths to inline markdown + download link."""
        def _replace(match):
            path = match.group(0)
            name = path.split("/")[-1]
            return self._image_md(name)

        return re.sub(r"(/[\w./~-]*\.(?:png|jpe?g|webp|gif))", _replace, text)

    def _attach_latest_image(self):
        """Fallback: attach the most recent file from the static image server."""
        base = self.valves.IMAGES_BASE_URL.rstrip("/")
        try:
            idx = requests.get(f"{base}/", timeout=5)
            names = re.findall(r'href="([^"]+\.(?:png|jpe?g|webp|gif))"', idx.text)
            if not names:
                return

            def _epoch(n):
                m = re.search(r"_(\d{10,})\.", n)
                return int(m.group(1)) if m else 0

            best = max(names, key=_epoch)
            yield self._chunk({"content": "\n\n" + self._image_md(best) + "\n"})
        except Exception:
            return

    def _images_from_result(self, result_text: str):
        """Extract image paths from a tool result and attach them with download links."""
        paths = re.findall(r"([\w/.-]*\.(?:png|jpe?g|webp|gif))", result_text)
        seen = set()
        for p in paths:
            name = p.split("/")[-1]
            if name in seen:
                continue
            seen.add(name)
            yield self._chunk({"content": "\n\n" + self._image_md(name) + "\n"})

    def pipe(self, user_message: str, model_id: str, messages: list, body: dict):
        base = self.valves.HERMES_BASE_URL.rstrip("/")
        headers = {
            "Authorization": f"Bearer {self.valves.HERMES_API_KEY}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": "hermes-agent",
            "messages": messages,
            "stream": True,
        }
        try:
            resp = requests.post(
                f"{base}/chat/completions",
                headers=headers,
                json=payload,
                stream=True,
                timeout=600,
            )
            resp.raise_for_status()
        except Exception as e:
            yield self._chunk({"content": f"Error connecting to Hermes: {e}"})
            return

        # image_generate pending attachment of its result
        pending_image = False

        for raw in resp.iter_lines(decode_unicode=True):
            if not raw:
                continue
            raw = raw.strip()
            if not raw.startswith("data:"):
                continue
            data = raw[5:].strip()
            if data == "[DONE]":
                break
            try:
                obj = json.loads(data)
            except Exception:
                continue

            # Tool event from an UNPATCHED Hermes API server:
            # {"tool": ..., "toolCallId": ..., "status": "running"|"completed", "label": ..., "result": ...}
            if isinstance(obj, dict) and "tool" in obj and "status" in obj:
                status = obj.get("status")
                tool = obj.get("tool", "")
                if status == "running":
                    label = obj.get("label") or tool
                    yield self._chunk({"reasoning_content": f"🛠️ {tool}: {label}\n"})
                elif status == "completed":
                    result = obj.get("result", "")
                    result_str = "" if result is None else str(result)
                    if len(result_str) > self.valves.MAX_RESULT_CHARS:
                        result_str = (
                            result_str[: self.valves.MAX_RESULT_CHARS]
                            + f"\n… [truncated: {len(result_str)} chars]"
                        )
                    yield self._chunk({"reasoning_content": f"✅ result:\n{result_str}\n\n"})
                    if tool == "image_generate":
                        yield from self._attach_latest_image()
                continue

            # Standard OpenAI chunk (patched API server: reasoning_content already translated)
            if obj.get("object") != "chat.completion.chunk":
                continue
            choices = obj.get("choices") or []
            if not choices:
                continue
            delta = choices[0].get("delta") or {}

            rc = delta.get("reasoning_content")
            if rc:
                if "image_generate" in rc:
                    pending_image = True
                if pending_image and ("✅" in rc or "result" in rc[:25]):
                    yield from self._images_from_result(rc)
                    pending_image = False
                yield self._chunk({"reasoning_content": rc})

            c = delta.get("content")
            if c:
                fixed = self._fix_image_paths(c)
                if fixed:
                    yield self._chunk({"content": fixed})
